<script type="text/javascript" runat="server">
var MoConfRewrite = {
	Rules:[
		{
			LookFor:/^\/index\.html$/igm,
			SendTo:"/?m=home&a=index"
		},
		{
			LookFor:/^\/update\.html$/igm,
			SendTo:"/?m=home&a=update"
		},
		{
			LookFor:/^\/guest(\-(\d+))?\.html(.*?)$/igm,
			SendTo:"/?m=home&a=guest&page=$2$3"
		},
		{
			LookFor:/^\/links\.html$/igm,
			SendTo:"/?m=home&a=links"
		},
		{
			LookFor:/^\/cats\/(([\d\,]+)|([a-zA-Z]+))(\/)?$/igm,
			SendTo:"/?m=home&a=cats&cat=$1"
		},
		{
			LookFor:/^\/cats\/(([\d\,]+)|([a-zA-Z]+))\/(\d+)(\/)?$/igm,
			SendTo:"/?m=home&a=cats&cat=$1&page=$4"
		},
		{
			LookFor:/^\/(atom|feed|sitemap|rss)(\/([\d\,]+))?(\/)?$/igm,
			SendTo:"/?m=home&a=rss&type=$1&catid=$3"
		},
		{
			LookFor:/^\/photos\/(\d+)(\/)?$/igm,
			SendTo:"/?m=home&a=photos&id=$1"
		},
		{
			LookFor:/^\/post\/(\d+)(\/(\d+))?\.html(.*?)$/igm,
			SendTo:"/?m=home&a=show&id=$1&page=$3$4"
		},
		{
			LookFor:/^\/tag\/([\w\-]+)\.html$/igm,
			SendTo:"/?m=home&a=tag&keyword=$1"
		},
		{
			LookFor:/^\/library\/(.+?)(\/(\d+))?\.html$/igm,
			SendTo:"/?m=home&a=library&keyword=$1&page=$3"
		},
		{
			LookFor:/^\/search\/(.+?)(\/(\d+))?(\/)?$/igm,
			SendTo:"/?m=home&a=search&keyword=$1&page=$3"
		},
		{
			LookFor:/^\/tag\/([\w\-]+)\/(\d+)\.html$/igm,
			SendTo:"/?m=home&a=tag&keyword=$1&page=$2"
		}
	]
};
</script>