<%
Dim MO_ROOT,MO_APP, MO_CORE, MO_TEMPLATE_NAME, MO_TEMPLATE_SPLIT, MO_TEMPLATE_PERX,MO_TABLE_PERX,MO_CACHE_DIR,MO_CACHE,MO_LIB_CACHE,MO_REWRITE_MODE,MO_APP_NAME
Dim MO_DEBUG,MO_COMPILE_CACHE,MO_CHARSET,MO_METHOD_CHAR,MO_ACTION_CHAR,MO_DATABASE_PATH,MO_PRE_LIB,MO_TAG_LIB,MO_END_LIB,MO_DIRECT_OUTPUT,MO_COMPILE_CACHE_EXPIRED,MO_COMPILE_STRICT,MO_PREETY_HTML
MO_ROOT = "/"
MO_APP_NAME = "App"
MO_APP = "/App/"
MO_CORE = "/Mo/"
MO_CACHE= false
MO_CACHE_DIR = ""
MO_TEMPLATE_NAME = "default"
MO_TEMPLATE_SPLIT = "/"
MO_TEMPLATE_PERX = "html"
MO_TABLE_PERX = "Mo_"
MO_DEBUG= true
MO_SHOW_SERVER_ERROR= true
MO_COMPILE_CACHE= true
MO_COMPILE_CACHE_EXPIRED = 0
MO_COMPILE_STRICT = false
MO_CHARSET = "UTF-8"
MO_METHOD_CHAR = "m"
MO_ACTION_CHAR = "a"
MO_PRE_LIB = ""
MO_TAG_LIB = ""
MO_END_LIB = ""
MO_DIRECT_OUTPUT = false
MO_LIB_CACHE = false
MO_REWRITE_MODE = ""
MO_PREETY_HTML = false
%>